# This file was generated by the `rails generate sharing_tags:install` command.

SharingTags.configure do

  # global configuration
  title         "Global site title"
  description   "Global site description"
  page_url      { root_url }
  image         { image_url('img.jpg') }

  # # for switch context call `sharing_tags.switch_context_to(:user)` in controller action
  # context :user do
  #   title         "User site title"
  #   description  "User site description"
  #   page_url     { profile_url }
  # end

end