language: ruby
before_install: gem install bundler
cache: bundler
rvm:
  - 2.0.0
  - 2.1.3
  - 2.2.0

notifications:
  email:
    recipients:
      - kr00lix@gmail.com
    on_failure: change
    on_success: never

sudo: false