# Generators are not automatically loaded by Rails
require 'generators/sharing_tags/install/install_generator'

describe SharingTags::Generators::InstallGenerator, type: :generator do

  # Tell the generator where to put its output (what it thinks of as Rails.root)
  destination File.expand_path('../../tmp', __FILE__)
  teardown :cleanup_destination_root

  before do
    prepare_destination
    run_generator
  end

  describe 'initializer' do
    let(:initializer) { content_for('config/initializers/sharing_tags.rb') }
    subject { file 'config/initializers/sharing_tags.rb' }

    it "creates a sharing_tags initializer" do
      is_expected.to exist
    end

    it "generates .rspec" do
      expect(file('config/initializers/sharing_tags.rb')).to exist
    end

    it "generates config/initializers/sharing_tags.rb" do
      generator_command_notice = / This file was generated by the `rails generate sharing_tags:install` command./m
      expect(initializer).to match(generator_command_notice)
    end
  end

  describe 'assets' do
    pending
    # subject { file 'app/controllers/sessions_controller.rb'}

    # it { is_expected_to have_method :index }
  end

  describe 'view' do
    pending
    # subject { file 'app/views/sessions/new.html.erb'}
    #
    # it { is_expected_to have_correct_syntax }

  end
end



